export const SpeakerData = [
	{
		id: 0,
		name: "Adrian Cockroft",
		title: "VP Cloud Architecture Strategy AWS",
		urlToIcon: "/images/real1.jpeg",
	},
	{
		id: 1,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy2.jpeg",
	},
	{
		id: 2,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy3.jpeg",
	},
	{
		id: 3,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy4.jpeg",
	},
	{
		id: 4,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy5.jpeg",
	},
	{
		id: 5,
		name: "Rachel Obstler",
		title: "VP, Product Management PagerDuty",
		urlToIcon: "/images/real1.jpeg",
	},
	{
		id: 6,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy6.jpeg",
	},
	{
		id: 7,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy7.jpeg",
	},
	{
		id: 8,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy4.jpeg",
	},
	{
		id: 9,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy2.jpeg",
	},
	{
		id: 10,
		name: "Rachel Obstler",
		title: "VP, Product Management PagerDuty",
		urlToIcon: "/images/real2.jpeg",
	},
	{
		id: 11,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy3.jpeg",
	},
	{
		id: 12,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy8.jpeg",
	},
	{
		id: 13,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy5.jpeg",
	},
	{
		id: 14,
		name: "Interested in Speaking ?",
		title: "Apply for CFP !",
		urlToIcon: "/images/dummy6.jpeg",
	},
	{
		id: 15,
		name: "Jon Snow",
		title: "Author, Researcher, Founder IT Revolution",
		urlToIcon: "/images/real1.jpeg",
	},
];
