export default [
	{
		sessionName: `Day 1 Keynote`,
		speaker: [{
            name: "Adrian Cockroft",
            role: "VP Cloud Architecture Strategy at AWS",
            speakerImage: "https://drive.google.com/file/d/1cFOVDMG_JQMOx0eVsGjC-Ek-U-ubfTVS/view?usp=sharing",
            companyLogo: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Faawa.info%2Fwp-content%2Fuploads%2F2019%2F05%2Faws-logo.png&f=1&nofb=1",
        }],
		time: "8:00 AM",
		description: "",
        tags: ["Keynote"],
        id: 0,
	},
	{
        time: "9:00 AM",
        duration: '(45min)',
		speaker1: {
            sessionName: `[Session 1] A powerful framework for network chaos experiments note`,
            speaker: [{
                name: "Andreas Krivas",
                role: "Engineering Manager",
                speakerImage: "https://drive.google.com/file/d/1qDTRIfc9A1H101VwS-LcWjKetwvmfZaU/view?usp=sharing",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(123, 143, 234, 0.12)',
            tags: ["Chaos Engineering", "Observability"],
            id: 1,
        },
        speaker2: {
            sessionName: `[Session 2] Building on System Resilience with Chaos Engineering for Serverless Applications on AWS`,
            speaker: [{
                name: "Renaldi Gondosubroto",
                role: "Founder & Project Leader",
                speakerImage: "https://drive.google.com/file/d/1dgdQdmKKzHeGybhmLXuE4xNRIJzux1Q6/view?usp=sharing",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(255, 8, 88, 0.2)',
            tags: ["Chaos Engineering"],
            id: 2,
        }
	},
	{
        time: "9:45 AM",
        duration: "(45min)",
		speaker1: {
            sessionName: `[Session 3] Create Chaos in Databases`,
            speaker: [{
                name: "Vadim Tkachenko",
                role: "C0-Founder & CTO",
                speakerImage: "https://drive.google.com/file/d/1VeXyT-J90GYxc36-dW37Vtz4Bmm-40EE/view?usp=sharing",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(234, 220, 133, 0.2)',
            tags: ["Chaos Engineering", "Observability"],
            id: 3,
        },
        speaker2: {
            sessionName: `[Session 4] Chaos Engineering in Telco Cloudnative Infra`,
            speaker: [{
                name: "Vaibhav Chopra",
                role: "Engineering Manager",
                speakerImage: "https://drive.google.com/file/d/13OYd_o9sdyzQMSUVkT0GMAU6bQ4HPQ7Z/view?usp=sharing",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(226, 115, 23, 0.2)',
            tags: ["Chaos Engineering"],
            id: 4,
        }
	},
	{
        time: "10:00 AM",
        duration: "(45min)",
	    speaker1: {	
            sessionName: `[Session 5] Improve Application Resiliency with AWS Fault Injection Simulator`,
            speaker: [{
                name: "Gunnar Grosch",
                role: "Senior Developer Advocate",
                speakerImage: "",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(255, 142, 38, 0.3)',
            tags: ["Chaos Engineering", "Observability"],
            id: 5,
        },
        speaker2: {
            sessionName: `[Session 6] Creating a learning culture`,
            speaker: [{
                name: "Amir Shaked",
                role: "Senior VP of R&D",
                speakerImage: "",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(240, 31, 64, 0.15)',
            tags: ["Chaos Engineering", "Observability"],
            id: 6,
        }
	},
	{
        time: "10:45 AM",
        duration: "(45min)",
		speaker1: {
            sessionName: `[Session 7] Event-Driven Chaos Injection`,
            speaker: [{
                name: "Raj Babu Das",
                role: "Software Engineer",
                speakerImage: "",
                companyLogo: "",
            }, {
                name: "Soumya Ghosh Dastidar",
                role: "Software Engineer",
                speakerImage: "",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(0, 99, 255, 0.05)',
            tags: ["Chaos Engineering", "Observability"],
            id: 7,
        },
        speaker2: {
            sessionName: `[Session 8] Chaos Engineering for Cloud Native Security`,
            speaker: [{
                name: "Kennedy A Torkura",
                role: "Cloud Security Engineer",
                speakerImage: "",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(82, 145, 202, 0.2)',
            tags: ["Chaos Engineering"],
            id: 8,
        }
	},
	{
        time: "1:15 PM",
        duration: '(45min)',
		speaker1: {
            sessionName: `[Session 9] Chaos Engineering the Chaos Engineers`,
            speaker: [{
                name: "Jason Yee",
                role: "Director of Advocacy",
                speakerImage: "",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(12, 131, 95, 0.3)',
            tags: ["Chaos Engineering", "Observability"],
            id: 9,
        },
        speaker2: {
            sessionName: `[Session 10] Clear the ring for Chaos Engineering at Vertrieb Deutsche Bahn! One year sensations and attractions!`,
            speaker: [{
                name: "Maik Figura",
                role: "IT Consultant",
                speakerImage: "",
                companyLogo: "",
            },{ 
                name: "Oliver Kracht",
                role: "Implementation Lead",
                speakerImage: "",
                companyLogo: "",
            },{ 
                name: "Jonas vor dem Berge",
                role: "Implementation Lead",
                speakerImage: "",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(128, 251, 198, 0.2)',
            tags: ["Chaos Engineering"],
            id: 10,
        }
	},
	{
        time: "2:00 PM",
        duration: '30min',
		speaker1: {
            sessionName: `[Session 11] The Psychology of Chaos Engineering`,
            speaker: [{
                name: "Julie Gunderson",
                role: "DevOps Advocate",
                speakerImage: "",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(6, 172, 56, 0.2)',
            tags: ["Chaos Engineering", "Observability"],
            id: 11,
        },
        speaker2: {
            sessionName: `[Session 12] Introduction to OWASP`,
            speaker: [{
                name: "Gunnard Engebreth",
                role: "Senior Developer",
                speakerImage: "",
                companyLogo: "",
            }],
            description: "",
            background: 'rgba(5, 167, 225, 0.08)',
            tags: ["Chaos Engineering"],
        }
	},
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
	// {
	// 	sessionName: `Day 1 Keynote`,
	// 	speakerName: "Adrian Cockroft",
	// 	role: "VP Cloud Architecture Strategy at AWS",
	// 	time: "8:00 AM",
	// 	description: "",
	// 	tags: ["Keynote"],
	// 	speakerImage: "",
	// 	companyLogo: "",
	// },
];
