export default [
	{
		sessionName: `Day 1 Keynote`,
		speakerName: ["Adrian Cockroft"],
		role: ["VP Cloud Architecture Strategy at AWS"],
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 1] A powerful framework for network chaos experiments note`,
		speakerName: ["Andreas Krivas"],
		role: ["Engineering Manager"],
		time: "9:00 AM",
		description: "",
		tags: ["Chaos Engineering", "Observability"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 2] Building on System Resilience with Chaos Engineering for Serverless Applications on AWS`,
		speakerName: ["Renaldi Gondosubroto"],
		role: ["Founder & Project Leader"],
		time: "9:00 AM",
		description: "",
		tags: ["Chaos Engineering"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 3] Create Chaos in Databases`,
		speakerName: ["Andreas Krivas"],
		role: ["Engineering Manager"],
		time: "9:45 AM",
		description: "",
		tags: ["Chaos Engineering", "Observability"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 4] Chaos Engineering in Telco Cloudnative Infra`,
		speakerName: ["Vaibhav Chopra"],
		role: ["Engineering Manager"],
		time: "9:45 AM",
		description: "",
		tags: ["Chaos Engineering"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 5] Improve Application Resiliency with AWS Fault Injection Simulator`,
		speakerName: ["Gunnar Grosch"],
		role: ["Senior Developer Advocate"],
		time: "10:00 AM",
		description: "",
		tags: ["Chaos Engineering", "Observability"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 6] Creating a learning culture`,
		speakerName: ["Amir Shaked"],
		role: ["Senior VP of R&D"],
		time: "10:00 AM",
		description: "",
		tags: ["Chaos Engineering", "Observability"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 7] Event-Driven Chaos Injection`,
		speakerName: ["Raj Babu Das", "Soumya Ghosh Dastidar"],
		role: ["Software Engineer", "Software Engineer"],
		time: "10:45 AM",
		description: "",
		tags: ["Chaos Engineering", "Observability"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 8] Chaos Engineering for Cloud Native Security`,
		speakerName: ["Kennedy A Torkura"],
		role: ["Cloud Security Engineer"],
		time: "10:45 AM",
		description: "",
		tags: ["Chaos Engineering"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 9] Chaos Engineering the Chaos Engineers`,
		speakerName: ["Jason Yee"],
		role: ["Director of Advocacy"],
		time: "1:15 PM",
		description: "",
		tags: ["Chaos Engineering", "Observability"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 10] Clear the ring for Chaos Engineering at Vertrieb Deutsche Bahn! One year sensations and attractions!`,
		speakerName: ["Maik Figura", "Oliver Kracht", "Jonas vor dem Berge"],
		role: ["IT Consultant", "Implementation Lead", "Implementation Lead"],
		time: "1:15 PM",
		description: "",
		tags: ["Chaos Engineering"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 11] The Psychology of Chaos Engineering`,
		speakerName: ["Julie Gunderson"],
		role: ["DevOps Advocate"],
		time: "2:00 PM",
		description: "",
		tags: ["Chaos Engineering", "Observability"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `[Session 12] Introduction to OWASP`,
		speakerName: ["Gunnard Engebreth"],
		role: ["Senior Developer"],
		time: "2:00 AM",
		description: "",
		tags: ["Chaos Engineering"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
	{
		sessionName: `Day 1 Keynote`,
		speakerName: "Adrian Cockroft",
		role: "VP Cloud Architecture Strategy at AWS",
		time: "8:00 AM",
		description: "",
		tags: ["Keynote"],
		speakerImage: "",
		companyLogo: "",
	},
];
