version: 2.1
jobs:
  build-and-publish:
    docker:
      - image: circleci/node:alpine
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Login to dockerhub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build and push application's Docker image
          command: |
            docker build -t app -f Dockerfile .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag app "${REPO}:${CIRCLE_SHA1::6}"
              docker push "${REPO}:${CIRCLE_SHA1::6}"
            fi
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              docker tag app "${STAG_REPO}:ci-${CIRCLE_SHA1::6}"
              docker push "${STAG_REPO}:ci-${CIRCLE_SHA1::6}"
            fi
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-publish
