export const TableData = [
	{
		id: 0,
		detail: "Number Available",
		platinum: "2",
		gold: "5",
		silver: "10",
		bronze: "20",
	},
	{
		id: 1,
		detail: "Sponsor logo on the live stream",
		platinum: "Yes",
		gold: "No",
		silver: "No",
		bronze: "No",
	},
	{
		id: 2,
		detail:
			"Number Available5 minute sponsor pitch on the main live stream",
		platinum: "Yes",
		gold: "No",
		silver: "No",
		bronze: "No",
	},
	{
		id: 3,
		detail: "Virtual sponsor booth ",
		platinum: "Yes",
		gold: "Yes",
		silver: "No",
		bronze: "No",
	},
	{
		id: 4,
		detail: "Recognition on website (Logo and Link)",
		platinum: "Yes",
		gold: "Yes",
		silver: "Yes",
		bronze: "Yes",
	},
	{
		id: 5,
		detail: "Recognition in promotional emails",
		platinum: "Yes",
		gold: "Yes",
		silver: "Yes",
		bronze: "Yes",
	},
	{
		id: 6,
		detail: "(1) Customized sponsor ad before and after session* ",
		platinum: "Yes,Video Ad",
		gold: "Yes,Video Ad",
		silver: "Yes,Static Ad",
		bronze: "No",
	},
	{
		id: 7,
		detail: "Sponsor Slack Channel",
		platinum: "Yes,Multiple",
		gold: "Yes",
		silver: "Yes",
		bronze: "Yes",
	},
	{
		id: 8,
		detail: "Pre/Postmarketing email pitch",
		platinum: "Yes,Logo + 200 words",
		gold: "Yes,Logo + 100 words",
		silver: "Yes,Logo + 50 words",
		bronze: "No",
	},
	{
		id: 9,
		detail: "Slack Sponsor Pitch",
		platinum: "4 per day",
		gold: "3 per day",
		silver: "2 per day",
		bronze: "1 per day",
	},
	{
		id: 10,
		detail: "Logo on signage",
		platinum: "Large",
		gold: "Medium",
		silver: "Small",
		bronze: "Small",
	},
	{
		id: 11,
		detail:
			"Opportunity to provide (1) contributed article to key publications pre- or post-event",
		platinum: "Yes",
		gold: "Yes",
		silver: "Yes",
		bronze: "No",
	},
	{
		id: 12,
		detail: "Tweets from the official Chaos Carnival handle",
		platinum: "3 before the event,3 during the event",
		gold: "2 before the event,2 during the event",
		silver: "1 before the event,2 during the event",
		bronze: "2 during the event",
	},
	{
		id: 13,
		detail: "Virtual Swag Pitch",
		platinum: "Yes",
		gold: "Yes",
		silver: "Yes",
		bronze: "Yes",
	},
	{
		id: 14,
		detail: "Post-event data and leads report*",
		platinum: "Yes",
		gold: "Yes",
		silver: "Yes",
		bronze: "Yes",
	},
	{
		id: 15,
		detail: "15-minute technical demo or tutorial in a separate session",
		platinum: "Yes, Both Days",
		gold: "Yes, 1 Day",
		silver: "No",
		bronze: "No",
	},
	{
		id: 16,
		detail:
			"Sponsor recognition in post-conference thank you email to attendees",
		platinum: "Yes, Both Days",
		gold: "Yes,1 Day",
		silver: "No",
		bronze: "No",
	},
];
