export const SpeakerData = [
	{
		id: 0,
		name: "Vadim Tkachenko",
		title: "Co-Founder & CTO",
		company: "",
		urlToIcon: "/speakers/Vadim_Percona.jpg",
	},
	{
		id: 1,
		name: "Andreas Krivas",
		title: "Engineering Manager",
		company: "",
		urlToIcon: "/speakers/Andreas_ContainerSolutions.jpg",
	},
	{
		id: 2,
		name: "Gunnar Grosch",
		title: "Senior Developer Advocate",
		company: "",
		urlToIcon: "/speakers/Gunnar_AWS.jpg",
	},
	{
		id: 3,
		name: "Shelby Spees",
		title: "Developer Advocate",
		company: "",
		urlToIcon: "/speakers/Shelby_Honeycomb.jpg",
	},
	{
		id: 4,
		name: "Sumit Nagal",
		title: "Principal Engineer",
		company: "",
		urlToIcon: "/speakers/Sumit_Intuit.jpg",
	},
	{
		id: 5,
		name: "Olga Hall",
		title: "Global Head ,",
		company: "Amazon Video Availabilty",
		urlToIcon: "/speakers/Olga_Amazon.jpg",
	},
	{
		id: 6,
		name: "Michael Knyazev",
		title: "DevOps Consultant",
		company: "",
		urlToIcon: "/speakers/Michael_Iag.jpg",
	},
	{
		id: 7,
		name: "Raj Babu Das",
		title: "Software Engineer",
		company: "",
		urlToIcon: "/speakers/Raj_Mayadata.jpg",
	},
	{
		id: 8,
		name: "Julie Gunderson",
		title: "DevOps Advocate",
		company: "",
		urlToIcon: "/speakers/Julie_PagerDuty.jpg",
	},
	{
		id: 9,
		name: "Jason Yee",
		title: "Director of Advocacy",
		company: "",
		urlToIcon: "/speakers/Jason_Gremlin.jpg",
	},
	{
		id: 10,
		name: "Aravind Putrevu",
		title: "Developer Advocate",
		company: "",
		urlToIcon: "/speakers/Aravind_Elastic.jpg",
	},
	{
		id: 11,
		name: "Ramiro Berrelleza",
		title: "Founder & CEO",
		company: "",
		urlToIcon: "/speakers/Ramiro_Okteto.jpg",
	},
	{
		id: 12,
		name: "Amir Shaked",
		title: "Senior VP of R&D",
		company: "",
		urlToIcon: "/speakers/Amir_PerimeterX.jpg",
	},
	{
		id: 13,
		name: "Ana Margarita Medina",
		title: "Senior Chaos Engineer",
		company: "",
		urlToIcon: "/speakers/Ana_Gremlin.jpg",
	},
	{
		id: 14,
		name: "Carl Chesser",
		title: "Principal Engineer",
		company: "",
		urlToIcon: "/speakers/Carl_Cerner.jpg",
	},
	{
		id: 15,
		name: "Jürgen Etzlstorfer",
		title: "Technology Strategist",
		company: "",
		urlToIcon: "/speakers/Dynatrace_Speaker.jpg",
	},
	{
		id: 16,
		name: "Soumya Ghosh Dastidar",
		title: "Software Engineer",
		company: "",
		urlToIcon: "/speakers/Soumya_Mayadata.jpg",
	},
	{
		id: 17,
		name: "Yury Niño Roa",
		title: "Senior Site Reliability Engineer",
		company: "",
		urlToIcon: "/speakers/Yury_ADL.jpg",
	},
	{
		id: 18,
		name: "Haytham Elkhoja",
		title: "Chief Architect",
		company: "",
		urlToIcon: "/speakers/Haytham_IBM.jpg",
	},
	{
		id: 19,
		name: "Renaldi Gondosubroto",
		title: "Founder & Project Leader",
		company: "",
		urlToIcon: "/speakers/Renaldi_GRES.jpg",
	},
	{
		id: 20,
		name: "Gunnard Engebreth",
		title: "Senior Developer ",
		company: "",
		urlToIcon: "/speakers/Gunnard_PowerCode.jpg",
	},
	{
		id: 21,
		name: "Vaibhav Chopra",
		title: "Engineering Manager ",
		company: "",
		urlToIcon: "/speakers/Vaibhav_Orange.jpg",
	},
	{
		id: 22,
		name: "Piyush Verma",
		title: "Co-Founder & CTO",
		company: "",
		urlToIcon: "/speakers/Piyush_Last9.jpg",
	},
	{
		id: 23,
		name: "Eugenio Marzo",
		title: "DevOps Engineer",
		company: "",
		urlToIcon: "/speakers/Eugenio_SourceSense.jpg",
	},
	{
		id: 24,
		name: "Maik Figura",
		title: "IT Consultant",
		company: "",
		urlToIcon: "/speakers/Maik_Codecentric.jpg",
	},
	{
		id: 25,
		name: "Delphine Joyneer",
		title: "Senior Software Engineer",
		company: "",
		urlToIcon: "/speakers/Delphine_Wipro.jpg",
	},
	{
		id: 26,
		name: "Kennedy A Torkura",
		title: "Cloud Security Engineer",
		company: "",
		urlToIcon: "/images/dummy4.jpeg",
	},
];
