export const SpeakerData = [
	{
		id: 0,
		name: "Vadim Tkachenko",
		title: "Co-Founder & CTO",
		company: "",
		urlToIcon: "/speakers/Vadim_Percona-min.jpg",
	},
	{
		id: 1,
		name: "Chinmay Gaikwad",
		title: "Technical Evangelist",
		company: "",
		urlToIcon: "/speakers/Chinmay_Epsagon-min.jpg",
	},
	{
		id: 2,
		name: "Shelby Spees",
		title: "Developer Advocate",
		company: "",
		urlToIcon: "/speakers/Shelby_Honeycomb-min.jpg",
	},
	{
		id: 3,
		name: "Gunnar Grosch",
		title: "Senior Developer Advocate",
		company: "",
		urlToIcon: "/speakers/Gunnar_AWS-min.jpg",
	},
	{
		id: 4,
		name: "Sumit Nagal",
		title: "Principal Engineer",
		company: "",
		urlToIcon: "/speakers/Sumit_Intuit-min.jpg",
	},
	{
		id: 5,
		name: "Delphine Joyneer",
		title: "Senior Software Engineer",
		company: "",
		urlToIcon: "/speakers/Delphine_Wipro-min.jpg",
	},
	{
		id: 6,
		name: "Raj Babu Das",
		title: "Software Engineer",
		company: "",
		urlToIcon: "/speakers/Raj_Mayadata-min.jpg",
	},
	{
		id: 7,
		name: "Jason Yee",
		title: "Director of Advocacy",
		company: "",
		urlToIcon: "/speakers/Jason_Gremlin-min.jpg",
	},
	{
		id: 8,
		name: "Olga Hall",
		title: "Global Head ,",
		company: "Amazon Video Availabilty",
		urlToIcon: "/speakers/Olga_Amazon-min.jpg",
	},
	{
		id: 9,
		name: "Michael Knyazev",
		title: "DevOps Consultant",
		company: "",
		urlToIcon: "/speakers/Michael_IAG-min.jpg",
	},
	{
		id: 10,
		name: "Aravind Putrevu",
		title: "Developer Advocate",
		company: "",
		urlToIcon: "/speakers/Aravind_Elastic-min.jpg",
	},
	{
		id: 11,
		name: "Andreas Krivas",
		title: "Engineering Manager",
		company: "",
		urlToIcon: "/speakers/Andreas_ContainerSolutions-min.jpg",
	},
	{
		id: 12,
		name: "Robert Barron",
		title: "AIOps, Technology Assets & Architecture",
		company: "",
		urlToIcon: "/speakers/Robert_IBM-min.jpg",
	},
	{
		id: 13,
		name: "Julie Gunderson",
		title: "DevOps Advocate",
		company: "",
		urlToIcon: "/speakers/Julie_PagerDuty-min.jpg",
	},
	{
		id: 14,
		name: "Carl Chesser",
		title: "Principal Engineer",
		company: "",
		urlToIcon: "/speakers/Carl_Cerner-min.jpg",
	},
	{
		id: 15,
		name: "Jürgen Etzlstorfer",
		title: "Technology Strategist",
		company: "",
		urlToIcon: "/speakers/Dynatrace_Speaker-min.jpg",
	},
	{
		id: 16,
		name: "Ana Margarita Medina",
		title: "Senior Chaos Engineer",
		company: "",
		urlToIcon: "/speakers/Ana_Gremlin-min.jpg",
	},
	{
		id: 17,
		name: "Amir Shaked",
		title: "Senior VP of R&D",
		company: "",
		urlToIcon: "/speakers/Amir_PerimeterX-min.jpg",
	},
	{
		id: 18,
		name: "Soumya Ghosh Dastidar",
		title: "Software Engineer",
		company: "",
		urlToIcon: "/speakers/Soumya_Mayadata-min.jpg",
	},
	{
		id: 19,
		name: "Ramiro Berrelleza",
		title: "Founder & CEO",
		company: "",
		urlToIcon: "/speakers/Ramiro_Okteto-min.jpg",
	},
	{
		id: 20,
		name: "Oliver Kracht",
		title: "Implementation Lead",
		company: "",
		urlToIcon: "/speakers/Oliver_DB-min.jpg",
	},
	{
		id: 21,
		name: "Piyush Verma",
		title: "Co-Founder & CTO",
		company: "",
		urlToIcon: "/speakers/Piyush_Last9-min.jpg",
	},
	{
		id: 22,
		name: "Yury Niño Roa",
		title: "Senior Site Reliability Engineer",
		company: "",
		urlToIcon: "/speakers/Yury_ADL-min.jpg",
	},
	{
		id: 23,
		name: "Vaibhav Chopra",
		title: "Engineering Manager ",
		company: "",
		urlToIcon: "/speakers/Vaibhav_Orange-min.jpg",
	},
	{
		id: 24,
		name: "Maik Figura",
		title: "IT Consultant",
		company: "",
		urlToIcon: "/speakers/Maik_Codecentric-min.jpg",
	},
	{
		id: 25,
		name: "Renaldi Gondosubroto",
		title: "Founder & Project Leader",
		company: "",
		urlToIcon: "/speakers/Renaldi_GRES-min.jpg",
	},
	{
		id: 26,
		name: "Kennedy A Torkura",
		title: "Cloud Security Engineer",
		company: "",
		urlToIcon: "/speakers/Kennedy_Mattermost-min.jpg",
	},
	{
		id: 27,
		name: "Eugenio Marzo",
		title: "DevOps Engineer",
		company: "",
		urlToIcon: "/speakers/Eugenio_SourceSense-min.jpg",
	},
	{
		id: 28,
		name: "Samar Sidharth",
		title: "Lead Software Engineer",
		company: "",
		urlToIcon: "/speakers/Samar_Orange-min.jpg",
	},
	{
		id: 29,
		name: "Jonas vor dem Berge",
		title: "Implementation Lead",
		company: "",
		urlToIcon: "/speakers/Jonas_DB-min.jpg",
	},
	{
		id: 30,
		name: "Gunnard Engebreth",
		title: "",
		company: "",
		urlToIcon: "/speakers/Gunnard-min.jpg",
	},
];
